CREATE TABLESPACE tbs_perm_01
DATAFILE 'tbs_perm_01.dat'
SIZE 10M
REUSE
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE TEMPORARY TABLESPACE tbs_temp_01
TEMPFILE 'tbs_temp_01.dbf'
SIZE 50M
AUTOEXTEND ON;

CREATE USER ${ORACLE_USER}
IDENTIFIED BY ${ORACLE_PASSWORD}
DEFAULT TABLESPACE tbs_perm_01
TEMPORARY TABLESPACE tbs_temp_01
QUOTA 500M on tbs_perm_01;

GRANT create session TO ${ORACLE_USER};
GRANT create table TO ${ORACLE_USER};
GRANT create view TO ${ORACLE_USER};
GRANT create any trigger TO ${ORACLE_USER};
GRANT create any procedure TO ${ORACLE_USER};
GRANT create sequence TO ${ORACLE_USER};
GRANT create synonym TO ${ORACLE_USER};
